//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaInventory.idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ingles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ingles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NovaInventory.idioma.ingles", typeof(ingles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password have to had a maximun of 8 numbers.
        /// </summary>
        internal static string AAAAAAAAADVICE {
            get {
                return ResourceManager.GetString("AAAAAAAAADVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Sellar.
        /// </summary>
        internal static string Actualizar_bodega {
            get {
                return ResourceManager.GetString("Actualizar_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reload Detail.
        /// </summary>
        internal static string ActuDet {
            get {
                return ResourceManager.GetString("ActuDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User&apos;s Administration.
        /// </summary>
        internal static string administracionusuarios {
            get {
                return ResourceManager.GetString("administracionusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Cellar .
        /// </summary>
        internal static string Agregar_bodega {
            get {
                return ResourceManager.GetString("Agregar_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add to Invoice.
        /// </summary>
        internal static string AgrFact {
            get {
                return ResourceManager.GetString("AgrFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a amount.
        /// </summary>
        internal static string andrea {
            get {
                return ResourceManager.GetString("andrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name:.
        /// </summary>
        internal static string apelli2 {
            get {
                return ResourceManager.GetString("apelli2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Last Names:.
        /// </summary>
        internal static string APELLIDOS {
            get {
                return ResourceManager.GetString("APELLIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user who made the purchase.
        /// </summary>
        internal static string barquero {
            get {
                return ResourceManager.GetString("barquero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a serial  number.
        /// </summary>
        internal static string barraza {
            get {
                return ResourceManager.GetString("barraza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a show purchase.
        /// </summary>
        internal static string brix {
            get {
                return ResourceManager.GetString("brix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a provider.
        /// </summary>
        internal static string bt_pro {
            get {
                return ResourceManager.GetString("bt_pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Email.
        /// </summary>
        internal static string btenviar_Correo {
            get {
                return ResourceManager.GetString("btenviar_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a restore password.
        /// </summary>
        internal static string btn_adcontra {
            get {
                return ResourceManager.GetString("btn_adcontra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a business Administration.
        /// </summary>
        internal static string btn_ademp {
            get {
                return ResourceManager.GetString("btn_ademp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a inventory management.
        /// </summary>
        internal static string btn_adin {
            get {
                return ResourceManager.GetString("btn_adin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users Management.
        /// </summary>
        internal static string btn_adusu {
            get {
                return ResourceManager.GetString("btn_adusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a articles.
        /// </summary>
        internal static string btn_art {
            get {
                return ResourceManager.GetString("btn_art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cellar.
        /// </summary>
        internal static string btn_bo {
            get {
                return ResourceManager.GetString("btn_bo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a shopping.
        /// </summary>
        internal static string btn_compra {
            get {
                return ResourceManager.GetString("btn_compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setting.
        /// </summary>
        internal static string btn_config {
            get {
                return ResourceManager.GetString("btn_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a root user settings.
        /// </summary>
        internal static string btn_configroot {
            get {
                return ResourceManager.GetString("btn_configroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate invoice.
        /// </summary>
        internal static string btn_generar {
            get {
                return ResourceManager.GetString("btn_generar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General Inventory.
        /// </summary>
        internal static string btn_inge {
            get {
                return ResourceManager.GetString("btn_inge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventory.
        /// </summary>
        internal static string btn_inv {
            get {
                return ResourceManager.GetString("btn_inv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Article.
        /// </summary>
        internal static string btn_mostrar {
            get {
                return ResourceManager.GetString("btn_mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a products.
        /// </summary>
        internal static string btn_productos {
            get {
                return ResourceManager.GetString("btn_productos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign off.
        /// </summary>
        internal static string btn_serar {
            get {
                return ResourceManager.GetString("btn_serar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Article.
        /// </summary>
        internal static string btnactualizar_producto {
            get {
                return ResourceManager.GetString("btnactualizar_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Provider.
        /// </summary>
        internal static string btnAgregar {
            get {
                return ResourceManager.GetString("btnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Article.
        /// </summary>
        internal static string btnAgregar_producto {
            get {
                return ResourceManager.GetString("btnAgregar_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Provider.
        /// </summary>
        internal static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Article.
        /// </summary>
        internal static string btneliminar_producto {
            get {
                return ResourceManager.GetString("btneliminar_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Provider.
        /// </summary>
        internal static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Photo.
        /// </summary>
        internal static string BTNSELECCIONARFOTOUSUAIRO {
            get {
                return ResourceManager.GetString("BTNSELECCIONARFOTOUSUAIRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See Provider.
        /// </summary>
        internal static string btnVer {
            get {
                return ResourceManager.GetString("btnVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Product.
        /// </summary>
        internal static string Buscar_Producto {
            get {
                return ResourceManager.GetString("Buscar_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add User.
        /// </summary>
        internal static string BUTON1 {
            get {
                return ResourceManager.GetString("BUTON1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show User.
        /// </summary>
        internal static string BUTON2 {
            get {
                return ResourceManager.GetString("BUTON2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overwrite User.
        /// </summary>
        internal static string BUTON3 {
            get {
                return ResourceManager.GetString("BUTON3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete User.
        /// </summary>
        internal static string BUTON4 {
            get {
                return ResourceManager.GetString("BUTON4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REPORT.
        /// </summary>
        internal static string BUTON5 {
            get {
                return ResourceManager.GetString("BUTON5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a show user.
        /// </summary>
        internal static string ca {
            get {
                return ResourceManager.GetString("ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cashier.
        /// </summary>
        internal static string Cajero {
            get {
                return ResourceManager.GetString("Cajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password:.
        /// </summary>
        internal static string CAMBIAAAAAAAAAAAAAAMELACLAAAAAAAAAAAVE {
            get {
                return ResourceManager.GetString("CAMBIAAAAAAAAAAAAAAMELACLAAAAAAAAAAAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        internal static string cantiDAD {
            get {
                return ResourceManager.GetString("cantiDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Form.
        /// </summary>
        internal static string Cerrar_Formulario {
            get {
                return ResourceManager.GetString("Cerrar_Formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idioma español.
        /// </summary>
        internal static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        internal static string check_correo {
            get {
                return ResourceManager.GetString("check_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        internal static string checkrecuperar {
            get {
                return ResourceManager.GetString("checkrecuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        internal static string chkenglish {
            get {
                return ResourceManager.GetString("chkenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        internal static string chkEnglish_proveedor {
            get {
                return ResourceManager.GetString("chkEnglish_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mandatory field**.
        /// </summary>
        internal static string cinco {
            get {
                return ResourceManager.GetString("cinco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        internal static string CLAAVE {
            get {
                return ResourceManager.GetString("CLAAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warehouse Code.
        /// </summary>
        internal static string Codigo_bodega {
            get {
                return ResourceManager.GetString("Codigo_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a photo.
        /// </summary>
        internal static string como_sea {
            get {
                return ResourceManager.GetString("como_sea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password:.
        /// </summary>
        internal static string CONFIRMAAAAALAPELOTUDO {
            get {
                return ResourceManager.GetString("CONFIRMAAAAALAPELOTUDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check Inventory.
        /// </summary>
        internal static string ConsultInvent {
            get {
                return ResourceManager.GetString("ConsultInvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user administration.
        /// </summary>
        internal static string cora_roto {
            get {
                return ResourceManager.GetString("cora_roto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email:.
        /// </summary>
        internal static string CORREEEEOOO {
            get {
                return ResourceManager.GetString("CORREEEEOOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string correo {
            get {
                return ResourceManager.GetString("correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Correp {
            get {
                return ResourceManager.GetString("Correp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string CREACION {
            get {
                return ResourceManager.GetString("CREACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a questions should not be repeated*.
        /// </summary>
        internal static string cuatro {
            get {
                return ResourceManager.GetString("cuatro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a product.
        /// </summary>
        internal static string daniel {
            get {
                return ResourceManager.GetString("daniel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a company.
        /// </summary>
        internal static string desamor {
            get {
                return ResourceManager.GetString("desamor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string Dirección {
            get {
                return ResourceManager.GetString("Dirección", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Availability.
        /// </summary>
        internal static string DIsponibilidad {
            get {
                return ResourceManager.GetString("DIsponibilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document:.
        /// </summary>
        internal static string DIUUU {
            get {
                return ResourceManager.GetString("DIUUU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select your questions.
        /// </summary>
        internal static string dos {
            get {
                return ResourceManager.GetString("dos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Sellar.
        /// </summary>
        internal static string Eliminar_bodega {
            get {
                return ResourceManager.GetString("Eliminar_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete of Detail.
        /// </summary>
        internal static string EliminFact {
            get {
                return ResourceManager.GetString("EliminFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company:.
        /// </summary>
        internal static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company that belong&apos;s to:.
        /// </summary>
        internal static string EMPRESADEPERTENECIMIEEENTO {
            get {
                return ResourceManager.GetString("EMPRESADEPERTENECIMIEEENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user names.
        /// </summary>
        internal static string enojada {
            get {
                return ResourceManager.GetString("enojada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send the email .
        /// </summary>
        internal static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Root User Configuration.
        /// </summary>
        internal static string EOOT {
            get {
                return ResourceManager.GetString("EOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State:.
        /// </summary>
        internal static string ESTADOS_UNIDOS {
            get {
                return ResourceManager.GetString("ESTADOS_UNIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a delete user.
        /// </summary>
        internal static string estare {
            get {
                return ResourceManager.GetString("estare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventory Existencies.
        /// </summary>
        internal static string Existencias_Inventario {
            get {
                return ResourceManager.GetString("Existencias_Inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bill Detail.
        /// </summary>
        internal static string FACturadetallE {
            get {
                return ResourceManager.GetString("FACturadetallE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created by.
        /// </summary>
        internal static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Bill.
        /// </summary>
        internal static string FinFact {
            get {
                return ResourceManager.GetString("FinFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Photo:.
        /// </summary>
        internal static string FOOOOOOOOOOTOOO {
            get {
                return ResourceManager.GetString("FOOOOOOOOOOTOOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shopping Form.
        /// </summary>
        internal static string formulario_compras {
            get {
                return ResourceManager.GetString("formulario_compras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a product category.
        /// </summary>
        internal static string gabriel {
            get {
                return ResourceManager.GetString("gabriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a purchase form.
        /// </summary>
        internal static string garcia {
            get {
                return ResourceManager.GetString("garcia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warehouse Management.
        /// </summary>
        internal static string Gestion_bodegas {
            get {
                return ResourceManager.GetString("Gestion_bodegas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a reset the password.
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a name of user.
        /// </summary>
        internal static string hh {
            get {
                return ResourceManager.GetString("hh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a payment type.
        /// </summary>
        internal static string hola {
            get {
                return ResourceManager.GetString("hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Product.
        /// </summary>
        internal static string id_art {
            get {
                return ResourceManager.GetString("id_art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        internal static string id_categoria {
            get {
                return ResourceManager.GetString("id_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider.
        /// </summary>
        internal static string id_proveedor {
            get {
                return ResourceManager.GetString("id_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert your email.
        /// </summary>
        internal static string Ingresa_correo {
            get {
                return ResourceManager.GetString("Ingresa_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intervention of the Admin.
        /// </summary>
        internal static string intervencion {
            get {
                return ResourceManager.GetString("intervencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a username.
        /// </summary>
        internal static string ira {
            get {
                return ResourceManager.GetString("ira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nit.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry.
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created by.
        /// </summary>
        internal static string label7 {
            get {
                return ResourceManager.GetString("label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cellar.
        /// </summary>
        internal static string lblcodigo_producto_seriado {
            get {
                return ResourceManager.GetString("lblcodigo_producto_seriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string lblCorreoElectronico {
            get {
                return ResourceManager.GetString("lblCorreoElectronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email.
        /// </summary>
        internal static string lblCorreoElectronico12 {
            get {
                return ResourceManager.GetString("lblCorreoElectronico12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string lblfecha {
            get {
                return ResourceManager.GetString("lblfecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        internal static string lblforma_de_pago {
            get {
                return ResourceManager.GetString("lblforma_de_pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Models.
        /// </summary>
        internal static string lblprecio {
            get {
                return ResourceManager.GetString("lblprecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a online.
        /// </summary>
        internal static string lblpri {
            get {
                return ResourceManager.GetString("lblpri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Code.
        /// </summary>
        internal static string lblproveedores {
            get {
                return ResourceManager.GetString("lblproveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter again the password.
        /// </summary>
        internal static string lblREpeatcontra {
            get {
                return ResourceManager.GetString("lblREpeatcontra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string lblUser1 {
            get {
                return ResourceManager.GetString("lblUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        internal static string lgbtn_iniciar {
            get {
                return ResourceManager.GetString("lgbtn_iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First User.
        /// </summary>
        internal static string lgbtnprimer {
            get {
                return ResourceManager.GetString("lgbtnprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string lgcontra {
            get {
                return ResourceManager.GetString("lgcontra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forget your password?.
        /// </summary>
        internal static string lgolvide {
            get {
                return ResourceManager.GetString("lgolvide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string lgusu {
            get {
                return ResourceManager.GetString("lgusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a delete.
        /// </summary>
        internal static string lol {
            get {
                return ResourceManager.GetString("lol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a unit price.
        /// </summary>
        internal static string maria {
            get {
                return ResourceManager.GetString("maria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a product model.
        /// </summary>
        internal static string mate {
            get {
                return ResourceManager.GetString("mate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required fields**.
        /// </summary>
        internal static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user management.
        /// </summary>
        internal static string mecago {
            get {
                return ResourceManager.GetString("mecago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a show.
        /// </summary>
        internal static string monti {
            get {
                return ResourceManager.GetString("monti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year of birth:.
        /// </summary>
        internal static string NACIMIENTODEAGUACRISTAL {
            get {
                return ResourceManager.GetString("NACIMIENTODEAGUACRISTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a phone.
        /// </summary>
        internal static string nadie_me_quiere {
            get {
                return ResourceManager.GetString("nadie_me_quiere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N° Bill.
        /// </summary>
        internal static string nFactura {
            get {
                return ResourceManager.GetString("nFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code or Name of product.
        /// </summary>
        internal static string Nombre_producto {
            get {
                return ResourceManager.GetString("Nombre_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider name.
        /// </summary>
        internal static string nombre_proveedor {
            get {
                return ResourceManager.GetString("nombre_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a model.
        /// </summary>
        internal static string nose_mo {
            get {
                return ResourceManager.GetString("nose_mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        internal static string nueva_contraseña {
            get {
                return ResourceManager.GetString("nueva_contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a new Password.
        /// </summary>
        internal static string nuevacontra {
            get {
                return ResourceManager.GetString("nuevacontra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of user.
        /// </summary>
        internal static string odio {
            get {
                return ResourceManager.GetString("odio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Picture:.
        /// </summary>
        internal static string PEREJILDEFACEBOOK {
            get {
                return ResourceManager.GetString("PEREJILDEFACEBOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a show user.
        /// </summary>
        internal static string por {
            get {
                return ResourceManager.GetString("por", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unit Price.
        /// </summary>
        internal static string PrecioUnitariooooo {
            get {
                return ResourceManager.GetString("PrecioUnitariooooo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segurity Questions.
        /// </summary>
        internal static string preguntas_seguridad {
            get {
                return ResourceManager.GetString("preguntas_seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legal Representative.
        /// </summary>
        internal static string pri_legal {
            get {
                return ResourceManager.GetString("pri_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string pribtn {
            get {
                return ResourceManager.GetString("pribtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string pribtn1 {
            get {
                return ResourceManager.GetString("pribtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string pridire {
            get {
                return ResourceManager.GetString("pridire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company email.
        /// </summary>
        internal static string priemal {
            get {
                return ResourceManager.GetString("priemal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Add logo.
        /// </summary>
        internal static string priexa {
            get {
                return ResourceManager.GetString("priexa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish Registration.
        /// </summary>
        internal static string Prifin {
            get {
                return ResourceManager.GetString("Prifin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data company.
        /// </summary>
        internal static string prigroup {
            get {
                return ResourceManager.GetString("prigroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numbers.
        /// </summary>
        internal static string Prigroup1 {
            get {
                return ResourceManager.GetString("Prigroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue registration.
        /// </summary>
        internal static string priguar {
            get {
                return ResourceManager.GetString("priguar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We start by registering the main company, enter the requested data.
        /// </summary>
        internal static string prilabel1 {
            get {
                return ResourceManager.GetString("prilabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click browse to upload your company logo.
        /// </summary>
        internal static string prilabel2 {
            get {
                return ResourceManager.GetString("prilabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company logo.
        /// </summary>
        internal static string prilogo {
            get {
                return ResourceManager.GetString("prilogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company name.
        /// </summary>
        internal static string prinom {
            get {
                return ResourceManager.GetString("prinom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Identification number.
        /// </summary>
        internal static string prinum {
            get {
                return ResourceManager.GetString("prinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone numbers.
        /// </summary>
        internal static string prinums {
            get {
                return ResourceManager.GetString("prinums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mail.
        /// </summary>
        internal static string ravia {
            get {
                return ResourceManager.GetString("ravia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover Password.
        /// </summary>
        internal static string Recuperarcontraseña {
            get {
                return ResourceManager.GetString("Recuperarcontraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Before the login.
        /// </summary>
        internal static string Regresar {
            get {
                return ResourceManager.GetString("Regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        internal static string Reporte {
            get {
                return ResourceManager.GetString("Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a make a purchase.
        /// </summary>
        internal static string sandor {
            get {
                return ResourceManager.GetString("sandor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update purchase.
        /// </summary>
        internal static string sara {
            get {
                return ResourceManager.GetString("sara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the method the reset your password .
        /// </summary>
        internal static string seleccione {
            get {
                return ResourceManager.GetString("seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update user .
        /// </summary>
        internal static string siempre {
            get {
                return ResourceManager.GetString("siempre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add user.
        /// </summary>
        internal static string solo {
            get {
                return ResourceManager.GetString("solo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select photo.
        /// </summary>
        internal static string solo_le_importa_lo_suyo {
            get {
                return ResourceManager.GetString("solo_le_importa_lo_suyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a states.
        /// </summary>
        internal static string solo_queria_atencion {
            get {
                return ResourceManager.GetString("solo_queria_atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Form.
        /// </summary>
        internal static string StringCerrar {
            get {
                return ResourceManager.GetString("StringCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        internal static string StringchkGestion_bodega {
            get {
                return ResourceManager.GetString("StringchkGestion_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Number:.
        /// </summary>
        internal static string TELEEEE {
            get {
                return ResourceManager.GetString("TELEEEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type of User:.
        /// </summary>
        internal static string TIPOSDEUSEEEER {
            get {
                return ResourceManager.GetString("TIPOSDEUSEEEER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supplier Management.
        /// </summary>
        internal static string toolStripButton1 {
            get {
                return ResourceManager.GetString("toolStripButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Form.
        /// </summary>
        internal static string toolStripButton2 {
            get {
                return ResourceManager.GetString("toolStripButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article.
        /// </summary>
        internal static string toolStripLabel1 {
            get {
                return ResourceManager.GetString("toolStripLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a enter your answer.
        /// </summary>
        internal static string tres {
            get {
                return ResourceManager.GetString("tres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user lastnames.
        /// </summary>
        internal static string tristesa {
            get {
                return ResourceManager.GetString("tristesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total to Pay.
        /// </summary>
        internal static string TtPagar {
            get {
                return ResourceManager.GetString("TtPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string turcios {
            get {
                return ResourceManager.GetString("turcios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a segurity questions.
        /// </summary>
        internal static string uno {
            get {
                return ResourceManager.GetString("uno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Names:.
        /// </summary>
        internal static string userrrrrrrrrrrrrrrrrrrrr {
            get {
                return ResourceManager.GetString("userrrrrrrrrrrrrrrrrrrrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string usu {
            get {
                return ResourceManager.GetString("usu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        internal static string usua {
            get {
                return ResourceManager.GetString("usua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string usuari {
            get {
                return ResourceManager.GetString("usuari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User:.
        /// </summary>
        internal static string USUARRRIO {
            get {
                return ResourceManager.GetString("USUARRRIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Load.
        /// </summary>
        internal static string usubtn {
            get {
                return ResourceManager.GetString("usubtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string usubtn1 {
            get {
                return ResourceManager.GetString("usubtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish the questions.
        /// </summary>
        internal static string usubtn2 {
            get {
                return ResourceManager.GetString("usubtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string usuC {
            get {
                return ResourceManager.GetString("usuC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documents.
        /// </summary>
        internal static string usud {
            get {
                return ResourceManager.GetString("usud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        internal static string usue {
            get {
                return ResourceManager.GetString("usue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statues.
        /// </summary>
        internal static string usues {
            get {
                return ResourceManager.GetString("usues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user Logo.
        /// </summary>
        internal static string usufoto {
            get {
                return ResourceManager.GetString("usufoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string usun {
            get {
                return ResourceManager.GetString("usun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Numbers.
        /// </summary>
        internal static string usunum {
            get {
                return ResourceManager.GetString("usunum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string usup {
            get {
                return ResourceManager.GetString("usup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        internal static string Usup2 {
            get {
                return ResourceManager.GetString("Usup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Tip.
        /// </summary>
        internal static string usut {
            get {
                return ResourceManager.GetString("usut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string usuu {
            get {
                return ResourceManager.GetString("usuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See Sellar.
        /// </summary>
        internal static string Ver_bodega {
            get {
                return ResourceManager.GetString("Ver_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a view kardex.
        /// </summary>
        internal static string verkardEX {
            get {
                return ResourceManager.GetString("verkardEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add.
        /// </summary>
        internal static string xd {
            get {
                return ResourceManager.GetString("xd", resourceCulture);
            }
        }
    }
}
