//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaInventory.idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ingles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ingles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NovaInventory.idioma.ingles", typeof(ingles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Sellar.
        /// </summary>
        internal static string Actualizar_bodega {
            get {
                return ResourceManager.GetString("Actualizar_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Cellar .
        /// </summary>
        internal static string Agregar_bodega {
            get {
                return ResourceManager.GetString("Agregar_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Article.
        /// </summary>
        internal static string btn_mostrar {
            get {
                return ResourceManager.GetString("btn_mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Article.
        /// </summary>
        internal static string btnactualizar_producto {
            get {
                return ResourceManager.GetString("btnactualizar_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Provider.
        /// </summary>
        internal static string btnAgregar {
            get {
                return ResourceManager.GetString("btnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Article.
        /// </summary>
        internal static string btnAgregar_producto {
            get {
                return ResourceManager.GetString("btnAgregar_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Provider.
        /// </summary>
        internal static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Article.
        /// </summary>
        internal static string btneliminar_producto {
            get {
                return ResourceManager.GetString("btneliminar_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Provider.
        /// </summary>
        internal static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See Provider.
        /// </summary>
        internal static string btnVer {
            get {
                return ResourceManager.GetString("btnVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idioma español.
        /// </summary>
        internal static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        internal static string chkenglish {
            get {
                return ResourceManager.GetString("chkenglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        internal static string chkEnglish_proveedor {
            get {
                return ResourceManager.GetString("chkEnglish_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warehouse Code.
        /// </summary>
        internal static string Codigo_bodega {
            get {
                return ResourceManager.GetString("Codigo_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string Dirección {
            get {
                return ResourceManager.GetString("Dirección", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Sellar.
        /// </summary>
        internal static string Eliminar_bodega {
            get {
                return ResourceManager.GetString("Eliminar_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created by.
        /// </summary>
        internal static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shopping Form.
        /// </summary>
        internal static string formulario_compras {
            get {
                return ResourceManager.GetString("formulario_compras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warehouse Management.
        /// </summary>
        internal static string Gestion_bodegas {
            get {
                return ResourceManager.GetString("Gestion_bodegas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        internal static string id_categoria {
            get {
                return ResourceManager.GetString("id_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider.
        /// </summary>
        internal static string id_proveedor {
            get {
                return ResourceManager.GetString("id_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nit.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry.
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Created by.
        /// </summary>
        internal static string label7 {
            get {
                return ResourceManager.GetString("label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cellar.
        /// </summary>
        internal static string lblcodigo_producto_seriado {
            get {
                return ResourceManager.GetString("lblcodigo_producto_seriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string lblfecha {
            get {
                return ResourceManager.GetString("lblfecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        internal static string lblforma_de_pago {
            get {
                return ResourceManager.GetString("lblforma_de_pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Models.
        /// </summary>
        internal static string lblprecio {
            get {
                return ResourceManager.GetString("lblprecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Code.
        /// </summary>
        internal static string lblproveedores {
            get {
                return ResourceManager.GetString("lblproveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        internal static string lgbtn_iniciar {
            get {
                return ResourceManager.GetString("lgbtn_iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First User.
        /// </summary>
        internal static string lgbtnprimer {
            get {
                return ResourceManager.GetString("lgbtnprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string lgcontra {
            get {
                return ResourceManager.GetString("lgcontra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forget your password?.
        /// </summary>
        internal static string lgolvide {
            get {
                return ResourceManager.GetString("lgolvide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string lgusu {
            get {
                return ResourceManager.GetString("lgusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider name.
        /// </summary>
        internal static string nombre_proveedor {
            get {
                return ResourceManager.GetString("nombre_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legal Representative.
        /// </summary>
        internal static string pri_legal {
            get {
                return ResourceManager.GetString("pri_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string pribtn {
            get {
                return ResourceManager.GetString("pribtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string pribtn1 {
            get {
                return ResourceManager.GetString("pribtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string pridire {
            get {
                return ResourceManager.GetString("pridire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company email.
        /// </summary>
        internal static string priemal {
            get {
                return ResourceManager.GetString("priemal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Add logo.
        /// </summary>
        internal static string priexa {
            get {
                return ResourceManager.GetString("priexa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish Registration.
        /// </summary>
        internal static string Prifin {
            get {
                return ResourceManager.GetString("Prifin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data company.
        /// </summary>
        internal static string prigroup {
            get {
                return ResourceManager.GetString("prigroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numbers.
        /// </summary>
        internal static string Prigroup1 {
            get {
                return ResourceManager.GetString("Prigroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue registration.
        /// </summary>
        internal static string priguar {
            get {
                return ResourceManager.GetString("priguar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We start by registering the main company, enter the requested data.
        /// </summary>
        internal static string prilabel1 {
            get {
                return ResourceManager.GetString("prilabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click browse to upload your company logo.
        /// </summary>
        internal static string prilabel2 {
            get {
                return ResourceManager.GetString("prilabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company logo.
        /// </summary>
        internal static string prilogo {
            get {
                return ResourceManager.GetString("prilogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company name.
        /// </summary>
        internal static string prinom {
            get {
                return ResourceManager.GetString("prinom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Identification number.
        /// </summary>
        internal static string prinum {
            get {
                return ResourceManager.GetString("prinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone numbers.
        /// </summary>
        internal static string prinums {
            get {
                return ResourceManager.GetString("prinums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        internal static string Reporte {
            get {
                return ResourceManager.GetString("Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Form.
        /// </summary>
        internal static string StringCerrar {
            get {
                return ResourceManager.GetString("StringCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma Español.
        /// </summary>
        internal static string StringchkGestion_bodega {
            get {
                return ResourceManager.GetString("StringchkGestion_bodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supplier Management.
        /// </summary>
        internal static string toolStripButton1 {
            get {
                return ResourceManager.GetString("toolStripButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Form.
        /// </summary>
        internal static string toolStripButton2 {
            get {
                return ResourceManager.GetString("toolStripButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Article.
        /// </summary>
        internal static string toolStripLabel1 {
            get {
                return ResourceManager.GetString("toolStripLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string usu {
            get {
                return ResourceManager.GetString("usu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last name.
        /// </summary>
        internal static string usua {
            get {
                return ResourceManager.GetString("usua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Load.
        /// </summary>
        internal static string usubtn {
            get {
                return ResourceManager.GetString("usubtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        internal static string usubtn1 {
            get {
                return ResourceManager.GetString("usubtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish the questions.
        /// </summary>
        internal static string usubtn2 {
            get {
                return ResourceManager.GetString("usubtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string usuC {
            get {
                return ResourceManager.GetString("usuC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documents.
        /// </summary>
        internal static string usud {
            get {
                return ResourceManager.GetString("usud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        internal static string usue {
            get {
                return ResourceManager.GetString("usue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statues.
        /// </summary>
        internal static string usues {
            get {
                return ResourceManager.GetString("usues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user Logo.
        /// </summary>
        internal static string usufoto {
            get {
                return ResourceManager.GetString("usufoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string usun {
            get {
                return ResourceManager.GetString("usun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Numbers.
        /// </summary>
        internal static string usunum {
            get {
                return ResourceManager.GetString("usunum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string usup {
            get {
                return ResourceManager.GetString("usup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        internal static string Usup2 {
            get {
                return ResourceManager.GetString("Usup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Tip.
        /// </summary>
        internal static string usut {
            get {
                return ResourceManager.GetString("usut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string usuu {
            get {
                return ResourceManager.GetString("usuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See Sellar.
        /// </summary>
        internal static string Ver_bodega {
            get {
                return ResourceManager.GetString("Ver_bodega", resourceCulture);
            }
        }
    }
}
